# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#    - name: 'wps invite'
#      run: python main.py _wps_invite
#

name: quark checkin

on:
  push:  # 推送时执行
    branches:
      - main
  schedule:  # 定时执行
    - cron: '45 */12 * * *'

jobs:
  checkin:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
    - name: 'quark_checkin'
      run: |
        python checkIn_Quark.py
        #python note163.py ${{secrets.YOUDAO_USER}} ${{secrets.YOUDAO_PASSWD}}
        #python note163.py ${{secrets.YOUDAO_USER2}} ${{secrets.YOUDAO_PASSWD2}}
        
        
        
